<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerAddressesRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CustomerAddressesRepository extends EntityRepository
{
}
