admin_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: app.user.controller.security:loginAction
        _app_options:
            template: "admin/security/login.html.twig"
            form: 'AdminBundle\Form\Type\AdminSecurityLoginType'

admin_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: app.user.controller.security:checkAction

admin_logout:
    path: /logout
    methods: [GET]
    
admin_resetting_request:
    path: /resetting/request
    methods: [GET, POST]
    defaults:
        _controller: app.controller.admin_user:resettingRequestAction
        _app_options:
            template: "admin/resetting/resettingRequest.html.twig"
            redirect: admin_login
            email_params: {from: "%admin_resetting_email.from%", route: "%admin_resetting_email.route%", template: "%admin_resetting_email.template%"}

admin_resetting_reset:
    path: /resetting/reset/{token}
    methods: [GET, POST]
    defaults:
        _controller: app.controller.admin_user:resettingResetAction
        _app_options:
            template: "admin/resetting/resettingReset.html.twig"
            redirect: admin_dashboard

admin_change_password:
    path: /change-password
    methods: [GET, POST]
    defaults:
        _controller: app.controller.admin_user:changePasswordAction
        _app_options:
            template: "admin/changePassword/changePassword.html.twig"
            redirect: admin_dashboard

admin_impersonate_user:
    path: /impersonate/{username}
    defaults:
        _controller: 'app.controller.admin_impersonate_site_user:impersonateAction'
        username: $username

admin_customer_change_password:
    path: /customer/{id}/change-password
    methods: [GET, POST]
    defaults:
        id: $id
        _controller: app.controller.site_user:changePasswordAction
        _app_options:
            form: 'AdminBundle\Form\Type\CustomerChangePasswordType'
            template: "admin/customer/changePassword.html.twig"
            redirect: admin_customer_index