imports:
    - { resource: config.yml }

parameters:
    email_sender: "postmaster@app6b8d3e36f7864da3b5aac5ce497a6678.mailgun.org"
    http_protocol: https

doctrine:
    dbal:
        url: "%env(CLEARDB_DATABASE_URL)%"
        #host: "%env(DATABASE_HOST)%"
        #port: "%env(DATABASE_PORT)%"
        #dbname: "%env(DATABASE_NAME)%"
        #user: "%env(DATABASE_USER)%"
        #password: "%env(DATABASE_PASS)%"
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

swiftmailer:
    host: "%env(MAILGUN_SMTP_SERVER)%"
    username: "%env(MAILGUN_SMTP_LOGIN)%"
    password: "%env(MAILGUN_SMTP_PASSWORD)%"
    port: "%env(MAILGUN_SMTP_PORT)%"
    sender_address: "%env(MAILGUN_SMTP_LOGIN)%"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            #path: '%kernel.logs_dir%/%kernel.environment%.log'
            path: 'php://stderr' # to heroku
            level: debug
        console:
            type: console
            process_psr_3_messages: false