site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

site_portal:
    resource: '@SiteBundle/Controller/Portal'
    prefix: /portal

site_user:
    resource: "@SiteBundle/Resources/config/routing_user.yml"

admin:
    resource: '@AdminBundle/Controller'
    type: annotation
    prefix: /admin

admin_user:
    resource: '@AdminBundle/Resources/config/routing_user.yml'
    prefix: /admin
