# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html

parameters:
    app.security.admin_regex: "^/admin"
    app.security.site_regex: "^/"

security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        admin_user_provider:
            id: app.admin_user_provider.email_or_name_based
        site_user_provider:
            id: app.site_user_provider.cnpj_or_email_based
        in_memory_admin:
            memory:
                users:
                    admin:
                        password: '@123#rci$'
                        roles: [ROLE_ADMINISTRATION_ACCESS]
    
    encoders:
        UserBundle\Model\User: bcrypt
    
    firewalls:

        admin:
            provider: admin_user_provider
            switch_user: true
            context: admin
            pattern: "%app.security.admin_regex%"
            form_login:
                provider: admin_user_provider
                login_path: admin_login
                check_path: admin_login_check
                failure_path: admin_login
                default_target_path: admin_dashboard
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%secret%"
                path: /admin
                name: APP_ADMIN_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: admin_logout
                target: admin_login
            anonymous: true

        site:
            provider: site_user_provider
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
            context: site
            pattern: "%app.security.site_regex%"
            form_login:
                provider: site_user_provider
                login_path: site_login
                check_path: site_login_check
                failure_path: site_login
                default_target_path: site_portal_dashboard
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%secret%"
                name: APP_SITE_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: site_logout
                target: site_homepage
                invalidate_session: false
            anonymous: true
    
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:

        - { path: "%app.security.admin_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%http_protocol%' }
        - { path: "%app.security.admin_regex%/resetting", role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%http_protocol%' }
        - { path: "%app.security.admin_regex%", role: ROLE_ADMINISTRATION_ACCESS, requires_channel: '%http_protocol%' }

        - { path: "%app.security.site_regex%portal", role: ROLE_USER, requires_channel: '%http_protocol%' }
        - { path: "%app.security.site_regex%", role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%http_protocol%' }
