# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.canonicalizer:
        class: AppBundle\Util\Canonicalizer

    app.util.flash_bag:
        class: AppBundle\Util\FlashBag
        autowire: true

    app.util.pagination:
        class: AppBundle\Util\Pagination
        autowire: true
