<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BillRemessaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BillRemessaRepository extends EntityRepository
{
}
