<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BillStatusRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BillStatusRepository extends EntityRepository
{
}
