<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UfRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UfRepository extends EntityRepository
{
    public function findLatest()
    {
        return $this->queryLatest()
            ->getQuery()
            ->getResult();
    }

    public function queryLatest()
    {
        return $this->createQueryBuilder('uf')
            ->orderBy('uf.nome', 'asc');
    }
}
